name: Cron Test Dependencies

# Controls when the action will run.
# Everyday at 4:05
# See https://crontab.guru/#5_4_*_*_*
on:
  schedule:
    - cron: "5 4 * * *"

jobs:
  run:
    name: Run unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [macos, ubuntu, windows]
        include:
          - build: macos
            os: macos-latest
            SKIP_LIGHTGBM: True
          - build: ubuntu
            os: ubuntu-latest
            SKIP_LIGHTGBM: False
          - build: windows
            os: windows-latest
            SKIP_LIGHTGBM: False
        python-version: [3.8, 3.9, "3.10"]
    steps:
    - uses: actions/checkout@master

    - name: Get latest CMake and Ninja
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: latest
        ninjaVersion: latest

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      env:
        SKIP_LIGHTGBM: ${{ matrix.SKIP_LIGHTGBM }}
      run: |
        pip3 install --upgrade setuptools pip
        pip3 install ".[all]"

    - name: Run linters
      env:
        SKIP_LIGHTGBM: ${{ matrix.SKIP_LIGHTGBM }}
      run: |
        pre-commit install
        pre-commit run --all-files

    - name: Run (unit) tests
      env:
        SKIP_LIGHTGBM: ${{ matrix.SKIP_LIGHTGBM }}
      run: |
        pytest --cov=probatus/binning --cov=probatus/metric_volatility --cov=probatus/missing_values --cov=probatus/sample_similarity --cov=probatus/stat_tests --cov=probatus/utils --cov=probatus/interpret/ --ignore==tests/interpret/test_inspector.py --cov-report=xml
        pyflakes probatus
