name: Cron Test Dependencies

on:
  schedule:
    # Every Sunday at 04:05 UTC.
    - cron: "5 4 * * 0"
  workflow_dispatch:

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
    with:
      upgrade-dependencies: true
