name: Development

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
    with:
      upload-coverage: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
